service: ifq-buddy
provider:
  name: aws
  runtime: python3.7
  region: eu-central-1
#  stage: dev

package:
 include:
   - app/**
   - functions/**
 exclude:
   - "**"

functions:
  sync:
    handler: functions/sync.handle
    timeout: 30
    environment:
      IFQ_USERNAME: ${ssm:/ifq_buddy/dev/ifq/username}
      IFQ_PASSWORD: ${ssm:/ifq_buddy/dev/ifq/password~true}
      OC_URL: ${ssm:/ifq_buddy/dev/oc/url}
      OC_USERNAME: ${ssm:/ifq_buddy/dev/oc/username}
      OC_PASSWORD: ${ssm:/ifq_buddy/dev/oc/password~true}
      TELEGRAM_TOKEN: ${ssm:/ifq_buddy/dev/telegram/token}
      TELEGRAM_CHAT_ID: ${ssm:/ifq_buddy/dev/telegram/chat_id}

    events:
      - schedule:
          name: ${self:service}-${opt:stage, self:provider.stage}-Sync
          rate: cron(0 5 * * ? *)
          enabled: true

plugins:
  - serverless-python-requirements
